### PR TITLE
birthday list added

### PR DESCRIPTION
**Pull request by ivanvolkoff**

### CODE REVIEW

**Review by AlexLazrag — APPROVED** [review]

**Review by DenislavTonkov — APPROVED** [review]
I approve this BDay

**Review by Narekoboss — APPROVED** [review]
Great stuff!

**Review by GrigorovN — APPROVED** [review]
Very good

**Review by BorisssIliev — APPROVED** [review]
ok pich

**Review by NinoTsenov — APPROVED** [review]

**Review by epxanr — APPROVED** [review]

**Comment by DanielaNikolovaPetrova** [comment]
I approve

**Pull request merged**
